import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../../components/Header'
import Image from 'next/image'
import Interests from '../../data/interests.json'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>UFinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}

export default Home
