import Head from 'next/head'
import React from 'react'

export interface Props {
  title: string
}

const HeadMetaData = (props: Props) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
        rel="stylesheet"
      />
    </Head>
  )
}

export default HeadMetaData
